### ISSUE TITLE
Specify ffmpeg code

### ISSUE THREAD

**Issue by killerlearner** [aNNiMON/ffmpegbot#2]
Where can I specify my own ffmpeg code and if it's given in repo from starting then how can I set to the one I want to use?

**Comment by killerlearner** [comment]
And if possible drive upload and direct link download to as tg only support max 2gb file

**Comment by aNNiMON** [comment]
You can define your ffmpeg options [here FFmpegCommandBuilder.java](https://github.com/aNNiMON/ffmpegbot/blob/f2c31b61156e473134230c7fd773d36e0fd92232/src/main/java/com/annimon/ffmpegbot/commands/ffmpeg/FFmpegCommandBuilder.java) and bot buttons for them [here ffmpegbot/parameters](https://github.com/aNNiMON/ffmpegbot/tree/f2c31b61156e473134230c7fd773d36e0fd92232/src/main/java/com/annimon/ffmpegbot/parameters) 

For Drive upload you can try this project https://github.com/WeebZoneIndia/Video-Encoder-Bot/tree/beta (beta branch).

**Comment by killerlearner** [comment]
I am getting errors in weebzone repo and it's owner has dropped it so he doesn't know how to solve!
 So does your repo support hevc .mkv file encoding in aac .mp4

**Comment by killerlearner** [comment]
I want to convert .mkv files into .MP4 with only one audio track specified like `-map 0:a:m:language:eng`.
Can you tell me your tg I'd I can ask there.

**Comment by aNNiMON** [comment]
@killerlearner I added Audio selector by language https://github.com/aNNiMON/ffmpegbot/tree/audio-stream-paramerter
But looks like Telegram stores mkv only as files. Bot works only with videos, video notes, voice messages and audios.

**Comment by killerlearner** [comment]
Can you add so I can keep files in bot after encoding instead of uploading in tg then we can use rclone to upload in cloud or any other api method 
And I can get mkv file using direct link in bot with wget cmd. Then which cmd should I use to encode the video to get video with only one stream audio I select like by selecting language code and subtitle removed
